services:
  chat:
    build: .
    volumes:
      - .:/app
      - ../../agenta-cli:/agenta-cli
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - MISTRAL_API_KEY=${MISTRAL_API_KEY}
      - COHERE_API_KEY=${COHERE_API_KEY}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - ANYSCALE_API_KEY=${ANYSCALE_API_KEY}
      - PERPLEXITYAI_API_KEY=${PERPLEXITYAI_API_KEY}
      - DEEPINFRA_API_KEY=${DEEPINFRA_API_KEY}
      - TOGETHERAI_API_KEY==${TOGETHERAI_API_KEY}
      - ALEPHALPHA_API_KEY=${ALEPHALPHA_API_KEY}
      - OPENROUTER_API_KEY=${OPENROUTER_API_KEY}
      - GROQ_API_KEY=${GROQ_API_KEY}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    networks:
      - agenta-network
    extra_hosts:
      - "host.docker.internal:host-gateway"
    labels:
      - "traefik.http.routers.chat.rule=PathPrefix(`/services/chat/`)"
      - "traefik.http.routers.chat.entrypoints=web"
      - "traefik.http.middlewares.chat-strip.stripprefix.prefixes=/services/chat"
      - "traefik.http.middlewares.chat-strip.stripprefix.forceslash=true"
      - "traefik.http.routers.chat.middlewares=chat-strip"
      - "traefik.http.services.chat.loadbalancer.server.port=80"
      - "traefik.http.routers.chat.service=chat"

networks:
  agenta-network:
    external: true
